#!/bin/bash

while read server
do
    echo "Patching $server..."

    ssh root@$server "yum clean all && yum update -y && yum clean all"

    if [ $? -eq 0 ]; then
        echo "$server patching completed"
    else
        echo "$server patching failed"
    fi

done < server.txt
