#!/bin/bash

SERVER_LIST="/home/neeraj/server.txt"

while read -r SERVER
do
    [[ -z "$SERVER" || "$SERVER" =~ ^# ]] && continue

    ssh -n -T -o BatchMode=yes "$SERVER" '
        hostname
        uptime
        uname -a
        date
    ' 2>/dev/null

done < "$SERVER_LIST"
