#!/bin/bash

SERVERS="server1 server2 server3 server4"
USERS="userid1 userid2 userid3"

for SERVER in $SERVERS
do
    echo "================================="
    echo "Checking server: $SERVER"
    echo "================================="

    for USER in $USERS
    do
        ssh $SERVER "grep ^$USER: /etc/passwd"
    done

    echo ""
done
